backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'news'
    label: '공지사항'
    i18n: true
    folder: 'content/news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

  - name: 'about'
    label: '학교소개'
    i18n: true
    folder: 'content/about'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'weight', name: 'weight', widget: 'string', i18n: true, hint: "입력된 숫자가 낮을수록, 항목은 메뉴 상위에 위치한다" }

  - name: 'contact'
    label: '문의하기'
    i18n: true
    folder: 'content/contact'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'weight', name: 'weight', widget: 'string', i18n: true, hint: "입력된 숫자가 낮을수록, 항목은 메뉴 상위에 위치한다" }

  - name: 'curriculum'
    label: '교과과정'
    i18n: true
    folder: 'content/curriculum'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'weight', name: 'weight', widget: 'string', i18n: true, hint: "입력된 숫자가 낮을수록, 항목은 메뉴 상위에 위치한다" }

  - name: 'news_menu'
    label: '공지 및 행사'
    i18n: true
    folder: 'content/news_menu'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'weight', name: 'weight', widget: 'string', i18n: true, hint: "입력된 숫자가 낮을수록, 항목은 메뉴 상위에 위치한다" }

  - name: 'involvment'
    label: '등록'
    i18n: true
    folder: 'content/involvment'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'weight', name: 'weight', widget: 'string', i18n: true, hint: "입력된 숫자가 낮을수록, 항목은 메뉴 상위에 위치한다" }

  - name: 'volunteer'
    label: '자원봉사'
    i18n: true
    folder: 'content/volunteer'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'weight', name: 'weight', widget: 'string', i18n: true, hint: "입력된 숫자가 낮을수록, 항목은 메뉴 상위에 위치한다" }

  - name: 'events'
    label: '월별행사'
    i18n: true
    folder: 'content/events'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

  - name: 'registration_pages'
    label: '등록 폼 용 페이지'
    i18n: true
    folder: 'content/registration_pages'
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, ko]
